spring.application.name=Library
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.cache.type=simple
spring.cache.cache-names=books,bookById,bookAvailability

logging.level.org.springframework.cache=TRACE