spring.application.name=library
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.cache.type=simple
spring.cache.cache-names=books,bookById,bookAvailability

logging.level.org.springframework.cache=TRACE

spring.config.import=vault://
spring.cloud.vault.uri=http://127.0.0.1:8200
spring.cloud.vault.token=root
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.default-context=library

app.jwt.access-expiration-seconds=900
app.jwt.refresh-expiration-seconds=1209600