spring.application.name=Library
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.cache.type=simple
spring.cache.cache-names=books,bookById,bookAvailability

logging.level.org.springframework.cache=TRACE

app.jwt.secret=p58MVw2NEw7LYgTIAvb/VZxw7BYg1LL4OwIOQhvkVYQ=
app.jwt.access-expiration-seconds=900
app.jwt.refresh-expiration-seconds=1209600